---
- hosts: prod
  become: yes
  vars_files:
    - vars/main.yml
  tasks:

  - name: Create upgrade dir
    file:
      path: /tmp/{{ tmp_dir }}
      state: directory
      owner: root
      group: root
      mode: 0777
    tags: create_upgrade_dir

  - name: Download the latest WAR file
    get_url:
      url: http://get.jenkins.io/war-stable/{{ app_version }}/{{ app_name }}.war
      dest: /tmp/{{ tmp_dir }}/{{ app_name }}.war
      owner: root
      group: root
      remote_src: yes
    tags: download
    register: uncompressed_app

  - name: Stop Jenkins service
    service:
      name: jenkins
      state: stopped
    tags: service_stop

  - name: Backup current installation
    copy:
      src: "{{ app_installation_path }}/{{ app_name }}.war"
      dest: "{{ app_installation_path }}/{{ app_name }}.war.{{ lookup('pipe', 'date +%Y%m%d') }}"
      owner: root
      group: root
      remote_src: yes
    tags: backup_installation

  - name: Move LTS WAR to Jenkins installation path
    ansible.builtin.shell: mv /tmp/{{ tmp_dir }}/{{ app_name }}.war {{ app_installation_path }}/{{ app_name }}.war

  - name: Start Jenkins service
    service:
      name: jenkins
      state: started
    tags: service_start

  - name: Clean temporary files
    file:
      path: /tmp/{{ tmp_dir }}
      state: absent
    tags: clean_tmp_files
